# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-11-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20171122_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除')], verbose_name='状态'),
        ),
    ]
